language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -q -r test_requirements.txt
  - pip install .
  - pip freeze
# command to run tests
script:
    - flake8 csob
    - mypy csob
    - python -m unittest discover
